[workspace]
members = ["comfy-quant-api", "comfy-quant-node"]
# Only check / build main crates by default (check all with `--workspace`)
default-members = ["comfy-quant-api"]
resolver = "2"


[workspace.dependencies]
anyhow = "1.0.89"
async-stream = "0.3.5"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"] }
