[package]
name = "comfy-quant-node"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-stream = { workspace = true }
futures = "0.3.30"
futures-util = "0.3.30"
tokio = { workspace = true }
tokio-stream = { workspace = true }
binance = { git = "https://github.com/wisespace-io/binance-rs.git", rev = "fe58a92" }
serde = { workspace = true }
serde_json = { workspace = true }
