[package]
name = "comfy-quant-api"
version = "0.1.0"
authors = ["Jeff <fei.code@gmail.com>"]
edition = "2021"

[dependencies]
comfy-quant-client = { path = "../comfy-quant-client" }
comfy-quant-data = { path = "../comfy-quant-data" }
anyhow = { workspace = true }
bon = { workspace = true }
flume = { workspace = true }
tokio = { workspace = true }
async-lock = { workspace = true }
futures = { workspace = true }
sqlx = { workspace = true }
rust_decimal = { workspace = true }
once_cell = "1.20"
config = "0.14"
serde = { workspace = true }
dotenvy = "0.15.7"
