[package]
name = "comfy-quant-api"
version = "0.1.0"
authors = ["Jeff <fei.code@gmail.com>"]
edition = "2021"

[dependencies]
comfy-quant-client = { path = "../comfy-quant-client" }
comfy-quant-data = { path = "../comfy-quant-data" }
# comfy-quant-node = { path = "../comfy-quant-node" }
anyhow = { workspace = true }
bon = { workspace = true }
flume = { workspace = true }
tokio = { workspace = true }
async-lock = { workspace = true }
futures = { workspace = true }
sqlx = { workspace = true }
rust_decimal = { workspace = true }
once_cell = { version = "1.20" }
config = { version = "0.14" }
serde = { workspace = true }
dotenvy = { version = "0.15.7" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = { workspace = true }
